import 'package:flutter/material.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedSinttulo1Widget.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedVectorWidget23.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedInicioWidget3.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedModeloTaycanWidget.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedVectorWidget22.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedModelo911Widget.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedModeloCayenneWidget.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedPorschelogo1Widget.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedAnuncio1Widget.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedMenuInferiorWidget1.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedModeloMacanWidget.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedModeloPanameraWidget.dart';
import 'package:flutterapp/act8androidapp/generatediniciowidget1/generated/GeneratedGg1Widget.dart';

/* Frame Inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInicioWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 781.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 115.0,
                child: GeneratedMenuInferiorWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.11495535714285714;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle7Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2898550724637681;

                  final double height =
                      constraints.maxHeight * 0.07254464285714286;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.36231884057971014,
                        y: constraints.maxHeight * 0.024553571428571428,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedInicioWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 25.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 365.0,
                height: 182.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 365.0,
                height: 187.0,
                child: GeneratedSinttulo1Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 53.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 48.0,
                child: GeneratedPorschelogo1Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 635.0,
                right: null,
                bottom: null,
                width: 365.0,
                height: 115.0,
                child: GeneratedAnuncio1Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 295.0,
                child: GeneratedGg1Widget(),
              ),
              Positioned(
                left: 243.0,
                top: 338.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 30.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 247.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 30.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 247.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 30.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 247.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 30.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 247.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 30.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 265.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 21.0,
                child: GeneratedModelo911Widget(),
              ),
              Positioned(
                left: 265.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 21.0,
                child: GeneratedModeloTaycanWidget(),
              ),
              Positioned(
                left: 265.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 21.0,
                child: GeneratedModeloMacanWidget(),
              ),
              Positioned(
                left: 258.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 23.0,
                child: GeneratedModeloCayenneWidget(),
              ),
              Positioned(
                left: 258.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 23.0,
                child: GeneratedModeloPanameraWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.033816425120772944;
                  double scaleX = (constraints.maxWidth * percentWidth) / 14.0;

                  double percentHeight = 0.022321428571428572;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 20.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.026570048309178744,
                        translateY: constraints.maxHeight * 0.23214285714285715,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget22())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.03864734299516908;
                  double scaleX = (constraints.maxWidth * percentWidth) / 16.0;

                  double percentHeight = 0.024553571428571428;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 22.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.9420289855072463,
                        translateY: constraints.maxHeight * 0.22879464285714285,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget23())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
