import 'package:flutter/material.dart';
import 'package:flutterapp/act8androidapp/generatedloginwidget/generated/GeneratedOlvidastetucontraseaWidget.dart';
import 'package:flutterapp/act8androidapp/generatedloginwidget/generated/GeneratedBienvenidodevueltaWidget.dart';
import 'package:flutterapp/act8androidapp/generatedloginwidget/generated/GeneratedCrearunacuentaWidget.dart';
import 'package:flutterapp/act8androidapp/generatedloginwidget/generated/GeneratedImputWidget.dart';
import 'package:flutterapp/act8androidapp/generatedloginwidget/generated/GeneratedImputWidget1.dart';
import 'package:flutterapp/act8androidapp/generatedloginwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/act8androidapp/generatedloginwidget/generated/GeneratedIngresalossiguientesdatosWidget.dart';
import 'package:flutterapp/act8androidapp/generatedloginwidget/generated/GeneratedBotonWidget.dart';
import 'package:flutterapp/act8androidapp/generatedloginwidget/generated/GeneratedImputWidget2.dart';
import 'package:flutterapp/act8androidapp/generatedloginwidget/generated/GeneratedMaskGroupWidget.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -77.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 615.0,
                child: GeneratedMaskGroupWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 500.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 68.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 37.0,
                child: GeneratedBienvenidodevueltaWidget(),
              ),
              Positioned(
                left: 68.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 30.0,
                child: GeneratedIngresalossiguientesdatosWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedImputWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedImputWidget1(),
              ),
              Positioned(
                left: 37.0,
                top: 664.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedImputWidget2(),
              ),
              Positioned(
                left: 99.0,
                top: 817.0,
                right: null,
                bottom: null,
                width: 218.0,
                height: 26.0,
                child: GeneratedOlvidastetucontraseaWidget(),
              ),
              Positioned(
                left: 134.0,
                top: 847.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 26.0,
                child: GeneratedCrearunacuentaWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedBotonWidget(),
              )
            ]),
      ),
    ));
  }
}
