import 'package:flutter/material.dart';
import 'package:flutterapp/act8androidapp/generatedajusteswidget10/generated/GeneratedMenuInferiorWidget5.dart';
import 'package:flutterapp/act8androidapp/generatedajusteswidget10/generated/GeneratedUpdatepanaWidget.dart';
import 'package:flutterapp/act8androidapp/generatedajusteswidget10/generated/GeneratedTitulosWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Ajustes
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAjustesWidget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 781.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 115.0,
                child: GeneratedMenuInferiorWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 103.0,
                child: GeneratedTitulosWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.4851650661892362;

                  final double height =
                      constraints.maxHeight * 0.6526156152997699;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.1570048309178744,
                        y: constraints.maxHeight * 0.16741071428571427,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedUpdatepanaWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
