import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/act8androidapp/generatedperfilwidget8/generated/GeneratedProfilepicpanaWidget.dart';
import 'package:flutterapp/act8androidapp/generatedperfilwidget8/generated/GeneratedTitulosWidget3.dart';
import 'package:flutterapp/act8androidapp/generatedperfilwidget8/generated/GeneratedMenuInferiorWidget4.dart';

/* Frame Perfil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPerfilWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 781.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 115.0,
                child: GeneratedMenuInferiorWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 103.0,
                child: GeneratedTitulosWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.2468040576879529;

                  final double height =
                      constraints.maxHeight * 0.6047157560076032;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.12318840579710146,
                        y: constraints.maxHeight * 0.19084821428571427,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedProfilepicpanaWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
