import 'package:flutter/material.dart';
import 'package:flutterapp/act8androidapp/generatedbotonwidget1/generated/GeneratedIniciarsesionWidget1.dart';
import 'package:flutterapp/act8androidapp/generatedbotonwidget1/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Component Boton
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBotonWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 340.0,
        height: 60.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 1.0;
                  double scaleX = (constraints.maxWidth * percentWidth) / 340.0;

                  double percentHeight = 1.0;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 60.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: 0,
                        translateY: constraints.maxHeight * 0.21666666666666667,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedRectangle3Widget1())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.34705882352941175;

                  final double height = constraints.maxHeight * 0.4;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.32941176470588235,
                        y: constraints.maxHeight * 0.43333317438761393,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIniciarsesionWidget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
