import 'package:flutter/material.dart';
import 'package:flutterapp/act8androidapp/generatedimputwidget3/generated/GeneratedRectangle2Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/act8androidapp/generatedimputwidget3/generated/GeneratedIngresatuemailWidget1.dart';

/* Component Imput
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImputWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 340.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle2Widget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.3911764705882353;

                final double height =
                    constraints.maxHeight * 0.4166666666666667;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.058823529411764705,
                      y: constraints.maxHeight * 0.3,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedIngresatuemailWidget1(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
