import 'package:flutter/material.dart';
import 'package:flutterapp/act8androidapp/generatedcrearpropiedadwidget/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/act8androidapp/generatedcrearpropiedadwidget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/act8androidapp/generatedcrearpropiedadwidget/generated/GeneratedOpcionesdepagoWidget.dart';
import 'package:flutterapp/act8androidapp/generatedcrearpropiedadwidget/generated/GeneratedPago1Widget.dart';
import 'package:flutterapp/act8androidapp/generatedcrearpropiedadwidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/act8androidapp/generatedcrearpropiedadwidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/act8androidapp/generatedcrearpropiedadwidget/generated/GeneratedMenuInferiorWidget2.dart';
import 'package:flutterapp/act8androidapp/generatedcrearpropiedadwidget/generated/GeneratedDolar1Widget.dart';
import 'package:flutterapp/act8androidapp/generatedcrearpropiedadwidget/generated/GeneratedTitulosWidget.dart';
import 'package:flutterapp/act8androidapp/generatedcrearpropiedadwidget/generated/GeneratedPricepanaWidget.dart';
import 'package:flutterapp/act8androidapp/generatedcrearpropiedadwidget/generated/GeneratedEscojelaopcionmascovenienteparatiWidget.dart';
import 'package:flutterapp/act8androidapp/generatedcrearpropiedadwidget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/act8androidapp/generatedcrearpropiedadwidget/generated/GeneratedTarjeta1Widget.dart';
import 'package:flutterapp/act8androidapp/generatedcrearpropiedadwidget/generated/GeneratedVectorWidget247.dart';

/* Frame Crear Propiedad
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCrearPropiedadWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 905.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 905.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 245, 245, 245),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 781.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 115.0,
                              child: GeneratedMenuInferiorWidget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.7665903579785628;

                                final double height =
                                    constraints.maxHeight * 0.33786135510186466;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.11594202898550725,
                                      y: constraints.maxHeight *
                                          0.1138121546961326,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedPricepanaWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 476.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 140.0,
                              child: GeneratedRectangle7Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 103.0,
                              child: GeneratedTitulosWidget(),
                            ),
                            Positioned(
                              left: 229.0,
                              top: 520.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 68.0,
                              child: GeneratedRectangle10Widget(),
                            ),
                            Positioned(
                              left: 61.0,
                              top: 520.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 67.0,
                              child: GeneratedRectangle11Widget(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 645.0,
                              right: null,
                              bottom: null,
                              width: 321.0,
                              height: 62.0,
                              child: GeneratedRectangle12Widget(),
                            ),
                            Positioned(
                              left: 49.0,
                              top: 434.0,
                              right: null,
                              bottom: null,
                              width: 318.0,
                              height: 68.0,
                              child: GeneratedRectangle13Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.0966183574879227;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        40.0;

                                double percentHeight = 0.04352679173590729;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        39.391746520996094;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.8768115942028986,
                                      translateY: constraints.maxHeight *
                                          0.12723214165281854,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget247())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 55.0,
                              top: 468.0,
                              right: null,
                              bottom: null,
                              width: 309.0,
                              height: 31.0,
                              child:
                                  GeneratedEscojelaopcionmascovenienteparatiWidget(),
                            ),
                            Positioned(
                              left: 72.0,
                              top: 520.0,
                              right: null,
                              bottom: null,
                              width: 95.0,
                              height: 63.0,
                              child: GeneratedTarjeta1Widget(),
                            ),
                            Positioned(
                              left: 59.0,
                              top: 434.0,
                              right: null,
                              bottom: null,
                              width: 303.0,
                              height: 40.0,
                              child: GeneratedOpcionesdepagoWidget(),
                            ),
                            Positioned(
                              left: 242.0,
                              top: 522.0,
                              right: null,
                              bottom: null,
                              width: 101.0,
                              height: 63.0,
                              child: GeneratedDolar1Widget(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 606.0,
                              right: null,
                              bottom: null,
                              width: 352.0,
                              height: 122.0,
                              child: GeneratedPago1Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
