import 'package:flutter/material.dart';
import 'package:flutterapp/act8androidapp/generatedfavoritoswidget6/generated/GeneratedThumb_up_altWidget.dart';
import 'package:flutterapp/act8androidapp/generatedfavoritoswidget6/generated/GeneratedTitulosWidget2.dart';
import 'package:flutterapp/act8androidapp/generatedfavoritoswidget6/generated/GeneratedFavoriteWidget.dart';
import 'package:flutterapp/act8androidapp/generatedfavoritoswidget6/generated/GeneratedPorsche_992_Carrera_4S_Genf_2019_1Y7A55611Widget.dart';
import 'package:flutterapp/act8androidapp/generatedfavoritoswidget6/generated/GeneratedMenuInferiorWidget3.dart';
import 'package:flutterapp/act8androidapp/generatedfavoritoswidget6/generated/GeneratedPorschelogo2Widget.dart';
import 'package:flutterapp/act8androidapp/generatedfavoritoswidget6/generated/GeneratedTaycan1Widget.dart';

/* Frame Favoritos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFavoritosWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 781.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 115.0,
                child: GeneratedMenuInferiorWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 103.0,
                child: GeneratedTitulosWidget2(),
              ),
              Positioned(
                left: 56.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 163.0,
                child: GeneratedPorschelogo2Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 199.0,
                child: GeneratedTaycan1Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 534.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 191.0,
                child:
                    GeneratedPorsche_992_Carrera_4S_Genf_2019_1Y7A55611Widget(),
              ),
              Positioned(
                left: 345.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 50.0,
                child: GeneratedFavoriteWidget(),
              ),
              Positioned(
                left: 348.0,
                top: 691.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 47.0,
                child: GeneratedThumb_up_altWidget(),
              )
            ]),
      ),
    ));
  }
}
